name: Fetch data.json from Google Drive

on:
  schedule:
    - cron: '0 0 * * *' # Chạy hàng ngày lúc 00:00 UTC
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Cài đặt các thư viện Python cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Tải file data.json từ Google Drive
      - name: Download data.json
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}
        run: |
          python fetch_data.py

      # Commit và push file data.json nếu có thay đổi
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m 'Update data.json from Google Drive' || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
